AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Jerusalem Embassy Appointments Telegram SAM template

Parameters:
  BotToken:
    Description: Telegram bot token
    Type: String
  ChannelId:
    Description: ID of the channel to post to
    Type: String
  StopAtNonBookableMonth:
    Description: >
      Option setting whether the bot should stop checking at a
      particular embassy when a month with no bookable dates is
      encountered.
    Type: String

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda.handler
      Runtime: nodejs12.x
      Timeout: 30
      Environment:
        Variables:
          BOT_TOKEN: !Ref BotToken
          CHANNEL_ID: !Ref ChannelId
          STOP_AT_NON_BOOKABLE_MONTH: !Ref StopAtNonBookableMonth
          DYNAMODB_TABLE: !Ref Table
          DEBUG: lambda
          DEBUG_HIDE_DATE: true
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Events:
        Trigger:
          Type: Schedule
          Properties:
            Schedule: "cron(0/5 * ? * MON-FRI *)"
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: InstanceId # We only need one record per lambda instance (1 total)
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
